### ISSUE TITLE
Add header in the output file with info about the run

### ISSUE THREAD

**Issue by anpefi** [anpefi/metapop2#22]
version, datafile, time & date, configuration file

**Comment by CORTEGANO** [comment]
I think we can close this issue now

**Comment by anpefi** [comment]
Another approach to deal with issues could be this:
When a fix is merged in develop, add "Fix/Close #22" in the commit message, add label "solved in develop" to the issue and keep the issue open. When the commit would be merged to the master then it automatically closes the issue. Keeping the issue open while the fix is not yet in the master can allow users to check what is expected to be added to the master/release "soon", and the label "solved in develop" indicates that they can use develop branch if want that feature (and allow us to know that issue has been already fixed. What do you think? We can try it until the next release.

**Comment by CORTEGANO** [comment]
It sounds reasonable. I reopen the issue then.
