### ISSUE TITLE
improve documentation of the output files

### ISSUE THREAD

**Issue by anpefi** [anpefi/metapop2#24]

**Comment by CORTEGANO** [comment]
I find that most of the output files were well documented. I revised and updated some of the documentation, specially that of `simStats.dat`, as well as the script `metapopResumeSims.R`. I also removed the `poolFile`, as it is redundant with the "SYNTHETIC POPULATION" section of the main output file.

**Comment by CORTEGANO** [comment]
I also checked for the "documentation" banch. I think we can safely delete it.
