### ISSUE TITLE
Management method He is wrong

### ISSUE THREAD

**Issue by anpefi** [anpefi/metapop2#33]
It is producing only one mate per subpopulation. Compare it with its equivalent Dynamic method.

**Comment by CORTEGANO** [comment]
I guess this issue can affect to the implementation of a new management method based on the effective number of alleles (Ae). However, I cannot see a missing variable, or loop over individuals, for management method He ( lines from 2379 to 2402 of `master:metapop.cpp`). Any idea on where can I find the relevant lines to help solving the issue?

Secondly, how is this issue related to the Dynamic method? by executing `grep --color=auto -C 5 dynamic src/*` on a terminal I cannot get a clue. Should I check the gene diversity management method instead? (I mean, lines from 2205 to 2258 of `master:metapop.cpp`). Thanks!!

**Comment by anpefi** [comment]
Well, I almost forgot about this. I need to recheck what I've done 8 months ago but this issue arise because in some escenarios I've checked there were only one mate per subpopulation when optimizing for He. When optimizing for total genetic diversity using the dynamic method, it usually has more than one mate per population. We thought that He was equivalent to genetic with lambda 1, with the advantage that He is far faster. I can't remember if I checked this (tomorrow I can say it) but what we need is to run some small examples with both methods and see of they yield equivalent results. Let me time to check what I've already done about this.

**Comment by anpefi** [comment]
This is the test I have done in February, and it gives different results for the mating matrix using He and dynamic method. Using this simple input2 and run both optimizations, it gave these results seen in the attached files. But now I'm not sure if I have discussed this with Armando or if just I became too busy these days with another tasks and left this unattended :s 
We should focus in this.



[test.He.Dyn.tar.gz](https://github.com/anpefi/metapop2/files/1504173/test.He.Dyn.tar.gz)

**Comment by anpefi** [comment]
Ok, I remember now. It is true that the He method is wrong, as it is just taking the mate with minimum coancestry in each population, providing a wild increase in inbreeding. This is why we actually used the dynamic method in the simulations. Perhaps we should remove the He method as it is useless

**Comment by CORTEGANO** [comment]
After talking to Armando, yes, this management method can be safely removed from the software (as you pointed out, it is equivalent to the genetic diversity optimization method).
